#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='^9' 
bspc rule -a telegram-desktop desktop='^5'
bspc rule -a opti state=floating
# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Autostart

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom

pkill picom
picom &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Pywal

. "${HOME}/.cache/wal/colors.sh"

# flashfocus

pkill flashfocus
flashfocus &

# set the wallpaper

~/.fehbg &

# Set the border colors.
# bspc config normal_border_color "$color15"
# bspc config active_border_color "$color15"
# bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
# bspc config presel_feedback_color "$color1"
